### ISSUE TITLE
Objects composed of more objects - how to select 

### ISSUE THREAD

**Issue by chromafunk** [pywavefront/PyWavefront#100]
Is it possible to select sub-objects in .obj files that are a group of objects ? I am totally new to this and the object I am working with has several sub-objects that compose a main .obj file. While testing ratcave yesterday, it had an in-built function to select which of the objects you want to work with. Is this possible via pywavefront ? Thanks

**Comment by einarf** [comment]
You can find the mesh info in `mesh_list` or `meshes` (dict)`. Currently there is one limitation (that will change in 2.x). All objects with the same material are grouped together in the same vertex list so the vertex data are stored in the materials themselves. 

Example here : https://github.com/pywavefront/PyWavefront/issues/87#issuecomment-464348971

**Comment by chromafunk** [comment]
thanks. And, another question ... is there a way to load .mtl files together with the .obj files somehow ?

**Comment by einarf** [comment]
mtl files are alredy automatically loaded if referenced in the obj file.

**Comment by chromafunk** [comment]
Thanks !
