### ISSUE TITLE
Problem with displaying textures

### ISSUE THREAD

**Issue by servusDei2018** [pywavefront/PyWavefront#107]
Until I commented out line `139` in `visualizer.py`, textures wouldn't show and instead, models were covered in stripe-like patterns, whose colors were somewhat like the texture they were supposed to have.

**System Details:**
ARMv7 Quad Core CPU @ 1.4GHz
Broadcom Videocore-IV GPU
1GB RAM

**OS Details:**
Debian 9 (Stretch)

Here's the code in visualizer.py that causes the problem. I found that by commenting-out the last line (`glTexParameterf(texture.image.target, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE)`), pywavefront rendered textures properly:
```python
def bind_texture(texture):
    """Draw a single texture"""
    if not getattr(texture, 'image', None):
        texture.image = load_image(texture.find())

    glEnable(texture.image.target)
    glBindTexture(texture.image.target, texture.image.id)
    glTexParameterf(texture.image.target, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE)
    #glTexParameterf(texture.image.target, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE)
```

**Comment by einarf** [comment]
How does the material for this object look like? It seems this is a result of not parsing out possible texture parameters.

Also, it looks like clamping should ideally be disabled by default.
```
-clamp on | off     # only render texels in the clamped 0-1 range (default off)
```

**Comment by servusDei2018** [comment]
@einarf, the texture is a PNG image. 

> It seems this is a result of not parsing out possible texture parameters?
I put `strict=True`, and there was no errors.

> Also, it looks like clamping should ideally be disabled by default.
It would be handy to be able to toggle those.

**Comment by einarf** [comment]
Yup that makes sense. I still need to know how your `mtl` file looks like 😄

**Comment by servusDei2018** [comment]
Contents of my .mtl:
```
#
#
newmtl base
Ns 96.078431
Ka 0.000000 0.000000 0.000000
Kd 0.629294 0.627706 0.716326
Ks 0.100000 0.100000 0.100000
Ni 1.000000
d 1.000000
illum 2
map_Kd Texture\\Base.png
map_bump Texture\\Base_normal.png


newmtl cube
Ns 96.078431
Ka 0.000000 0.000000 0.000000
Kd 0.377940 0.606339 0.643965
Ks 0.500000 0.500000 0.500000
Ni 1.000000
d 1.000000
illum 2
map_Kd Texture\\Cube.png
map_bump Texture\\Cube_n.png
```

**Comment by einarf** [comment]
Thank you. Think I will not do clamping by default and support the `-clamp on | off` texture option.

> In the original .mtl, I had to convert `map_Bump` to `map_bump` for the parser to handle it correctly.

That is a separate bug we can also try to squash right away.

**Comment by einarf** [comment]
Released 1.3.0 that should solve this issue:
https://github.com/pywavefront/PyWavefront/releases/tag/1.3.0

**Comment by einarf** [comment]
Please give the new version a go and close this issue if the issue is resolved.

Texture repeat can now be controlled with the `clamp` texture options.

The texture option is set in the mtl file.
```
map_Kd -clamp on texture.png
```

Clamping is now disabled by default and detected in visualization.

**Comment by servusDei2018** [comment]
Thanks @einarf , it works perfectly.
