### ISSUE TITLE
Unimplemented OBJ format statement 'Tf' on line 'Tf 1 1 1' and not show 3D picture

### ISSUE THREAD

**Issue by Dian-Yi** [pywavefront/PyWavefront#110]
when i run this code:
`import pywavefront
from pywavefront import visualization

obj = pywavefront.Wavefront('0421-1.obj')
visualization.draw(obj)`

i meet this error:
Unimplemented OBJ format statement 'Tf' on line 'Tf 1 1 1'
i delete "Tf 1 1 1" in .mtl file. it can run. but it cant show the 3D picture in the window

**Comment by einarf** [comment]
can you share this object/mtl file? The `Unimplemented` message is really just a warning. It might be that your object is drawing outside the camera. We need to add some kind of bounding box calculations to automatically place it in a reasonable spot.

**Comment by einarf** [comment]
If you get actual errors you are loading the object with `strict=True`.

Closing this issue for now. Be free to re-open or create a new issue in the future.
