### ISSUE TITLE
Merging all materials/textures into a single material in .mtl

### ISSUE THREAD

**Issue by sahandrez** [pywavefront/PyWavefront#113]
Hi, I want to know if it is possible to merge all textures in the .mtl file into one texture? The software I'm using only supports .mtl files with one material but the objects I'm loading have multiple materials. 
Thanks in advance.

**Comment by einarf** [comment]
It's not something pywavefront does, but it's technically possible if you merge all textures into a single one (atlas) and convert the texture coordinates. Maybe blender can do this?

**Comment by einarf** [comment]
Closing this for now. Please re-open or make a new issue if needed
