### ISSUE TITLE
PywavefrontException: Unimplemented OBJ format statement

### ISSUE THREAD

**Issue by morawi** [pywavefront/PyWavefront#114]
I can read this OBJ file with Windows 3D viewer, yet, I am having this error:

`PywavefrontException: Unimplemented OBJ format statement 'g' on line 'g Tshirt'`

Python 3.7
pywavefront.__version__
Out[12]: '1.3.2'

Any ideas?

**Comment by einarf** [comment]
It's just a warning. I need to hide those mesages by default. We don't support groups, but your object should load just fine.

**Comment by morawi** [comment]
I am not able to parse:

> 
> obj_3D.parse()
> Traceback (most recent call last):
> 
>   File "<ipython-input-14-ea830c6c66d8>", line 1, in <module>
>     obj_3D.parse()
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pywavefront\wavefront.py", line 84, in parse
>     self.parser.parse()
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pywavefront\obj.py", line 90, in parse
>     super(ObjParser, self).parse()
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pywavefront\parser.py", line 129, in parse
>     self.dispatcher.get(self.values[0], self.parse_fallback)()
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pywavefront\parser.py", line 47, in inner
>     func(*args, **kwargs)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pywavefront\parser.py", line 145, in parse_fallback
>     % (self.values[0], self.line.rstrip()))
> 
> PywavefrontException: Unimplemented OBJ format statement 'g' on line 'g Tshirt'

**Comment by einarf** [comment]
Don't use strict mode when loading the object
https://github.com/pywavefront/PyWavefront/blob/caa2013d7026dd484ac8c5ca8273f2d680196130/pywavefront/parser.py#L143-L148

**Comment by einarf** [comment]
Closing this for now. Please reopen or create new issue if you have any more questions or issues.
