### ISSUE TITLE
Accessing texture values

### ISSUE THREAD

**Issue by danperazzo** [pywavefront/PyWavefront#118]
Hello, I am trying to project my 3D model into a 2D projection (I have the camera intrinsics and pose). However, I do not understand how to get the RGB values of the faces, how do I do this?

**Comment by einarf** [comment]
In that context? This library is mainly focused on rendering the model(s) in opengl.

**Comment by danperazzo** [comment]
Oh, ok. Thank you! I was trying to use pywavelet to project a 3D model given a camera pose and intrinsics

**Comment by einarf** [comment]
Not familiar with pywavelet.

An example of how the low level data can be accessed can be found here: https://github.com/pywavefront/PyWavefront/issues/87#issuecomment-464348971

A lot can be done with that alone. It's not anyting fancy, but at least the data is easily accessible.

**Comment by danperazzo** [comment]
Ok, thank you!
