### ISSUE TITLE
Address groups and possibility to split mesh to submeshes by group

### ISSUE THREAD

**Issue by ttsesm** [pywavefront/PyWavefront#120]
I think that it would be nice to enhance the parser so that it can read groups and possibly split the model to sub meshes so that to get access to the individual objects of the model. 

Possibly this could be done in a tree/dictionary format going down from the root group to the child ones and then for each group node you can have the corresponding other properties e.g. vertices, faces, normals, materials, etc. grouped together or something similar.

**Comment by einarf** [comment]
I think trimesh might be a better option for manipulaton like this. Pywavefront was never really good at low level data manipulation. https://github.com/mikedh/trimesh
