### ISSUE TITLE
if any way export obj file ?

### ISSUE THREAD

**Issue by SuperCatO** [pywavefront/PyWavefront#121]

**Comment by einarf** [comment]
Maybe check out https://github.com/mikedh/trimesh instead

**Comment by SuperCatO** [comment]
Thank you for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pywavefront/PyWavefront"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月28日(星期一) 下午3:41
收件人:&nbsp;"pywavefront/PyWavefront"<PyWavefront@noreply.github.com&gt;;
抄送:&nbsp;"425124713"<425124713@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pywavefront/PyWavefront] if any way export obj file ? (#121)





 
Maybe check out https://github.com/mikedh/trimesh instead
