### ISSUE TITLE
Infinite loop while parsing obj file

### ISSUE THREAD

**Issue by Mikhail57** [pywavefront/PyWavefront#123]
I found a file that cannot be proceeded by the library. It's trying to parse, but cannot go over the first vertice

Sample `road1.obj` file:
```
# Blender v2.82 (sub 7) OBJ File: ''
# www.blender.org
mtllib tester.mtl
o Cube
v -0.500639 1.816088 1.058783
```
`tester.mtl`:
```
# Blender MTL File: 'road1.blend'
# Material Count: 0
```

**Comment by einarf** [comment]
This is merged now

**Comment by einarf** [comment]
1.3.3 should be on PyPI : https://pypi.org/project/PyWavefront/1.3.3/
