### ISSUE TITLE
Update test dependencies

### ISSUE THREAD

**Issue by Mikhail57** [pywavefront/PyWavefront#124]
Test dependencies, as well as CircleCI build machine Python version, are kinda old

Latest versions of test deps (listed in `test-requirements.txt`):
- `pytest` — `6.1.2`, current — `4.6.1`
- `mock` — `4.0.2`, current — `2.0.0`

Circle CI currently has an image with at least Python 3.6

**Comment by einarf** [comment]
We should probably just use github actions to quickly run the basic tests in all supported python versions

**Comment by einarf** [comment]
Also updated test requirements pinning each package to the current major version.

**Comment by einarf** [comment]
Made a separate issue for improving the CI stuff 😄

**Comment by einarf** [comment]
We run circleci with py3.8 + github actions with py35 -> py39. (flake8 + pytest)
