### ISSUE TITLE
Save Wavefront?

### ISSUE THREAD

**Issue by MrBenGriffin** [pywavefront/PyWavefront#128]
I was hoping to use PyWavefront to lint wavefront files, but I couldn't find a file save option.
Am I missing something?

Also, it would be excellent to allow exporting an internal model to wavefront.

**Comment by einarf** [comment]
I suspect trimesh is better for this: https://github.com/mikedh/trimesh

**Comment by MrBenGriffin** [comment]
Well, I don't always want to store triangular meshes. I have (coplanar) polygons, and the wavefront format supports that.

**Comment by MrBenGriffin** [comment]
However, you are probably right - I should really be using glTF.

**Comment by einarf** [comment]
Yes. wavefront is such an obscure format in 2021. This library was mainly created to load all kinds of obscure versions of wavefront files as a single library without any dependecies. There are plans for a 2.0 version having more features like you describe. The main goal was to load obj files and prepare triangulated data.

You can of course poke around in the internal data and do almost anything : https://github.com/pywavefront/PyWavefront/issues/87#issuecomment-464348971

**Comment by einarf** [comment]
Ups. closed it.

**Comment by einarf** [comment]
Also people use this library for the binary cache cutting down load times : https://github.com/pywavefront/PyWavefront#binary-cache

When working with large models it can sometimes take minute(s) to load with pure python.

**Comment by einarf** [comment]
Closing this for now.
