### ISSUE TITLE
vertex coloring

### ISSUE THREAD

**Issue by victoriapoghosyan** [pywavefront/PyWavefront#93]
I have object files that don't support per vertex coloring.Also I have .mtl files.Is it possible to get per vertex colors

**Comment by einarf** [comment]
You have an `obj` file without vertex color and you want to add colors programmatically?

**Comment by victoriapoghosyan** [comment]
Thank you for response. 
Example of .obj  file
mtllib 0000.mtl
v 0.354434 6.578578 -53.255806
v 0.372568 5.231034 -53.458153
.....
vt 0.483132 0.512387
vt 0.483085 0.508470
......
vn 0.367322 0.882667 0.293212
vn 0.236551 0.442998 0.864752
.....
g 0000
usemtl 0000
f 1/1/1 2/2/2 3/3/3
f 3/3/3 4/4/4 1/1/1
....

Example of .mtl file
newmtl 0000
Ka  0.15858 0.160808 0.113047
Kd  0.792901 0.804041 0.565233
Ks  0.47 0.47 0.47
d 1
Ns 0
illum 2
map_Kd 0000.jpg


Also I get vertices  (v in my .obj) with mesh.vertices, what is the way of getting uv vertices (vt in my .obj)?

**Comment by einarf** [comment]
I recently made an example here: https://github.com/pywavefront/PyWavefront/issues/87#issuecomment-464348971

The project definitely need more docs about this currently. I'm trying to resolve that soon.

**Comment by victoriapoghosyan** [comment]
Thanks a lot. I am closing this issue
