### ISSUE TITLE
uv texture map

### ISSUE THREAD

**Issue by victoriapoghosyan** [pywavefront/PyWavefront#94]
I am interested in creating uv texture map from .jpg and uv coords.
Is it possible with PyWavefront?
Thanks in advance

**Comment by einarf** [comment]
It's not made for creating textures or uv coords. The main focus (currently) is to load the files as they are. If you want to generate uv coordinates for simple objects such as planes and spheres, that is not too hard to do manually. In the vast majority of the cases I would recommend modifying the obj file itself with for example [Blender](https://www.blender.org/) either through python scripts or apply them manually.

Programmatically creating uv coordinates is not a trivial task unless you have very specific goals and types of objects.
