### ISSUE TITLE
how to get the normal vector of each face?

### ISSUE THREAD

**Issue by crcrcry** [pywavefront/PyWavefront#95]
I am interested in getting the normal vector of each face.
Is it possible with PyWavefront?
Or how to associate vertices, normals and faces?
Thanks in advance

**Comment by einarf** [comment]
We don't support actual face normals, but maybe that is a feature for 2.x.

Thankfully obtaining face normals is not that difficult when you have the raw data anyway. See https://github.com/pywavefront/PyWavefront/issues/87#issuecomment-464348971 for more hints about that.

You could simply do a cross product using the vertex position in each polygon using the two vectors between v0 and v1, v2.

**Comment by crcrcry** [comment]
Thank you!
