### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by Fivetuple** [pywavefront/PyWavefront#98]
Hi, using

import pywavefront
from pywavefront import visualization

obj = pywavefront.Wavefront('me.obj')
visualization.draw(obj)

I get AttributeError: 'ImageData' object has no attribute 'texture'.

What am I doing wrong?

**Comment by Fivetuple** [comment]
error line is 

 image = pyglet.image.load(name).texture

**Comment by einarf** [comment]
Do you have a full stack trace?

**Comment by einarf** [comment]
What version of pywavefront and pyglet? It might be related to the recent pyglet 1.4.x release?

**Comment by einarf** [comment]
@Fivetuple I think this issue is still relevant as the error message given to the user is very poor. Can you share what triggered this error? Did you resolve the issue considering it was closed?

**Comment by Fivetuple** [comment]
Hi,

pyglet is 1.4.1
pywavefront is 1.0.5

Sorry, I closed it accidentally.  I'll post the full trace tomorrow - not at work now.  The texture is held in a separate isomap.png file - how do I tell pywavefront about this file?

**Comment by einarf** [comment]
Textures are loaded from the same directory as the obj file. The texture referenced in the material can of course also use a relative path. This is pretty standard.

**Comment by einarf** [comment]
pywavefront 1.1.0 was released and should solve this issue. Pyglet 1.3 and 1.4 should work.

**Comment by einarf** [comment]
@Fivetuple All well on your side? Just making sure 😄

**Comment by Fivetuple** [comment]
Yes, fixed!  Thanks for checking.
