### ISSUE TITLE
can't reproduce examples

### ISSUE THREAD

**Issue by chromafunk** [pywavefront/PyWavefront#99]
```
import pywavefront
scene = pywavefront.Wavefront('something.obj')
```
```
    scene = pywavefront.Wavefront('something.obj')
AttributeError: module 'pywavefront' has no attribute 'Wavefront'
```
This is in a venv with python 3.6, I have tried installing via pip and also via setup.py, none works

**Comment by einarf** [comment]
Weird. Taking a look now.

**Comment by einarf** [comment]
```bash
$ git clone git@github.com:pywavefront/PyWavefront.git
$ cd PyWavefront/
$ python3.6 -m virtualenv env
$ . env/bin/activate
$ python --version
Python 3.6.8
$ python setup.py install
$ pip install pyglet
$ $ python examples/globe_complex.py
```
<img width="1136" alt="Screenshot 2019-08-14 at 16 53 03" src="https://user-images.githubusercontent.com/5418180/63031412-37bc7880-beb4-11e9-91e8-e492dcf1cc9b.png">

**Comment by chromafunk** [comment]
uhm, then I will just destroy the env an try. I'll confirm in a minute.

**Comment by einarf** [comment]
Works for me when installing from `pip` as well.

**Comment by chromafunk** [comment]
seems to work now, not sure why but I guess it was related to the env ... thanks :)

**Comment by einarf** [comment]
No problem 😄
